name: Java CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: "11"
                  distribution: "adopt"
            - name: run-tests
              working-directory: ./JHotDraw
              run: mvn test
            - name: build
              working-directory: ./JHotDraw
              run: mvn --batch-mode --update-snapshots verify
